/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */

var sum = 0;
var x = 1;
var y = 2;
var s = 0;

function fib(max) {
    while (x <= max) {
        if (x % 2 === 0) {
            sum += x;
        }
        s = x;
        x = y;
        y = s + y;
    }
    console.log(sum);
}

fib(4000000);